[theme]
primaryColor = "#004AAD"            # Biru utama Komdigi
backgroundColor = "#FFFFFF"         # Putih bersih
secondaryBackgroundColor = "#F4F6F8" # Abu-abu lembut
textColor = "#000000"               # Hitam teks
font = "sans serif"
