# =========================================
# Section [firebase_web] (untuk login.py / Auth REST API / client-side access)
# =========================================
[firebase_web]
firebase_api_key  = "AIzaSyCwPujDSQ2pABSc2tPm6FkzCZ-QVHPArHM"
authDomain = "inventarisasi-aset-microskill.firebaseapp.com"
projectId = "inventarisasi-aset-microskill"
storageBucket = "inventarisasi-aset-microskill.firebasestorage.app"
messagingSenderId = "1033425190340"
appId = "1:1033425190340:web:3d167c27cc5820f988f891"
measurementId = "G-64TJXSCCLZ"
admin_email = "yuliana111099@gmail.com"
